In [2]:
import numpy as np

In [6]:
a = np.zeros((3,3))
print(a)
b = np.ones((3,3))
print(b)
c = np.arange(1,10).reshape((3,3))
print(c)
print(c.shape, c.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3) int32


In [12]:
print(c[(1,1)])
print(c[0])

5
[1 2 3]


In [18]:
print(b+c)
print((2*b)*c)

print(c.mean(axis=0)) #среднее значение вдоль столбцов
print(c.mean(axis=1)) #среднее значение вдоль строк

c_min = c.min()
c_max = c.max()


c_normalized = (c - c_min) / (c_max - c_min)

print(c_normalized)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[4. 5. 6.]
[2. 5. 8.]
[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]
